---
title: "Pascual_K-means"
author: "Javi Pascual"
date: "2026-06-08"
output: html_document
---

## Packages ##
install.packages("cluster")

```{r chunk1, echo = TRUE}
## Set working directory ##
library(cluster)
library(ggplot2)
setwd("C:/Users/Blight/Desktop/S.Y 25-26 Term 3/LBBBI27")


## Dataframe and remove NAs##
my_data <- read.csv("morphology_data.csv")

remove_NA <- complete.cases(my_data)

head(my_data[remove_NA, ])

clean_data <- my_data[remove_NA, ]

```

```{r chunk2, echo = TRUE}
## Remove sex column and check for NAs ##
removesex_data <- my_data[ , c(1, 3:21)]

sum(is.na(removesex_data))
#Result must be zero#

## Scale data (while reading numeric values only) ##
removepop_data <- my_data[ , 3:21]
#remove pop column as well for scale() to work#

## Scale ##
data_scale <- scale(removepop_data)

## Set seed ##
set.seed(123)

## k-means cluster 3 with 25 centroids ##
kmeans_cluster <- kmeans(data_scale, centers = 3, nstart = 25)

## Print cluster assignment ##
print(head(kmeans_cluster$cluster))

## Print summary ##
kmeans_cluster

## Scatterplot ##
plot(data_scale[, 1:2], col = kmeans_cluster$cluster, pch = 19, main = "K-means Clustering Result")
```

```{r chunk3, echo = TRUE}
## LOOP ##
#library(ggplot2)
i <- 0
set.seed(123)
km_loop <- NULL
wss_values <- numeric(10)

for (i in 1:10) {
    set.seed(123)
    
    km_loop <- kmeans(data_scale, centers = i, nstart = 25)
    
    wss_values[i] <- km_loop$tot.withinss
}

## Elbow curve ##
elbow_data <- data.frame(K = 1:10, WSS = wss_values)

ggplot(elbow_data, aes(x = K, y = WSS)) + geom_point() + scale_x_continuous(breaks = 1:10) + geom_line()

#K = 3 is the optimal K#

## Repeat ##
## A6 ##
finalkmeans_cluster <- kmeans(data_scale, centers = 3, nstart = 25)

## A7 ##
print(head(finalkmeans_cluster$cluster))

## Print summary ##
finalkmeans_cluster

## A8 ##
plot(data_scale[, 1:2], col = finalkmeans_cluster$cluster, pch = 19, main = "Final K-means Clustering Result")
```






