---
title: "Pascual_PCA"
author: "Javi Pascual"
date: "2026-06-17"
output: html_document
---

```{r chunkA, echo=TRUE}
### Set working directory ###
setwd("C:/Users/Blight/Desktop/S.Y 25-26 Term 3/LBBBI27")

### Read as dataframe ###
my_data <- read.csv("Meneses_et.al_2026_Platymantis.csv")

### Subset data ###
reduced_data <- my_data[ , 10:34]

### Number of morphological features present ###
ncol(reduced_data)

# Result: [1] 25

### Remove NAs ###
remove_NA <- complete.cases(reduced_data)

head(reduced_data[remove_NA, ])

clean_data <- reduced_data[remove_NA, ]

### Scale data ###
scaled_data <- scale(clean_data)

### Pairwise correlations ###
cor_data <- cor(scaled_data)

round(cor_data, 2)

### Calculate eigenvectors ###
eigen_data <- eigen(cor_data)

### Calculate proportion of variance in % ###
provar_data <- eigen_data$values / sum(eigen_data$values)

prcnt_provar <- (eigen_data$values / sum(eigen_data$values)) * 100

eigen_vec <- eigen_data$vectors

scores_data <- scaled_data %*% eigen_vec

head(scores_data)

### Amount of principal components produced ###
length(eigen_data$values)

# Result: 25

### Proportion of variance explained by components 1-4 ###
prcnt_provar[1:4]

# Result: 29.858017 16.505790  8.614588  6.794091

sum(prcnt_provar[1:4])

# Result: 61.77249

```

```{r chunkB, echo=TRUE, fig.align ="center", fig.width=18, fig.height=8}

### Scree Plot ##
barplot(provar_data, names.arg = paste0("PC", 1:25), ylim = c(0, 1), col = "aquamarine", main = "Scree Plot on PCA", ylab = "Proportion of Variance")

### PCA ###

speciesplot_data <- as.factor(my_data$Species[remove_NA])

plot(scores_data[,1], scores_data[,2], xlab = "PC1", ylab = "PC2", main = "PCA Score Plot (PC1 vs PC2)", pch = 19, col = as.factor(speciesplot_data))

legend("topright", legend = levels(speciesplot_data), col = 1:2, pch = 15)

onetwo_PC <- eigen_data$vectors[ , 1:2]
onetwo_scale <- 3
onetwo_scaled <- onetwo_PC * onetwo_scale


### Biplot ###
par(mfrow = c(1, 2))

barplot(provar_data, names.arg = paste0("PC", 1:25), ylim = c(0, 1), col = "aquamarine", main = "Scree Plot on PCA", ylab = "Proportion of Variance")

plot(scores_data[,1], scores_data[,2], xlab = "PC1", ylab = "PC2", main = "PCA Score Plot with Eigenvector Loadings", pch = 19, col = speciesplot_data)

legend("topright", legend = levels(speciesplot_data), col = 1:3, pch = 15)

arrows(0, 0, onetwo_scaled[,1], onetwo_scaled[,2], col = "aquamarine", lwd = 2)

text(onetwo_scaled[,1], onetwo_scaled[,2], labels = colnames(clean_data), col = "orange", pos = 3)


```

```{r chunkC, echo=TRUE, warning=FALSE}
par(mfrow = c(1, 1))

### Broken-stick vs. PCA  ###
p <- ncol(speciesplot_data)

bs_func <- function(p){
  sapply(1:p, function(k){
    sum(1 / (k:p)) / p
  })
}

brok_stick <- bs_func(ncol(my_data[ , 1:length(provar_data)]))
brok_stick

compare <- data.frame(PC = paste0("PC", 1:length(provar_data)), observed = provar_data, BrokenStick = brok_stick)

compare

plot(provar_data, type = "b", pch = 19, ylim = c(0, max(provar_data)), xlab = "Principal Component", ylab = "Proportion of Variance", main = "Broken-Stick Analysis")

lines(brok_stick, type = "b", pch = 17, col = "aquamarine")

legend("topright", legend = c("Observed", "Broken Stick"), pch = c(19, 17), col = c("black", "aquamarine"))

### Barplot ###
library(PCAtest)

#using NA removed data
pca_result <- PCAtest(clean_data, 100, 100, 0.05, varcorr=FALSE, counter=FALSE, plot=TRUE)

#using NA removed and scaled data
pca_result <- PCAtest(scaled_data, 100, 100, 0.05, varcorr=FALSE, counter=FALSE, plot=TRUE)

### Interpretation ###
#The differences between the broken-stick model and the PCA test is that the former evaluates the eigenvalue against a null distribution based on geometric probability. In terms of the latter, it is a inferential statistic, meaning it evaluates the observed matrix against an empirical null distribution generated by permutation algorithm.

```
